const dataBase = [
        {
          code: 1,
          name: 'Tissot Everytime',
          price: 256,
          color: 'red',
          src: '../../assets/items/tissoteverytime.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 2,
          name: 'Royal London',
          price: 152,
          color: 'gold',
          src: '../../assets/items/royallondon.png',
          rating: 3,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Royal',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Англия',
        },
        {
          code: 3,
          name: 'Tissot PR 100 Sport',
          price: 432,
          color: 'white',
          src: '../../assets/items/tissotprsport.png',
          rating: 5,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 4,
          name: 'Tissot Everytyme Small',
          price: 203,
          color: 'grey',
          src: '../../assets/items/tissoteverytimesmall.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 5,
          name: 'Cassio',
          price: 126,
          color: 'grey',
          src: '../../assets/items/cassio.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 6,
          name: 'Tissot Couturier',
          price: 244,
          color: 'grey',
          src: '../../assets/items/tissotcouturier.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 7,
          name: 'Perrier Lannier',
          price: 256,
          color: 'white',
          src: '../../assets/items/perrierlannier.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Perrier',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Розовое золото',
          country: 'Франция',
        },
        {
          code: 8,
          name: 'Swiss Military Hannova',
          price: 346,
          color: 'brown',
          src: '../../assets/items/swissmilitary.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Swiss',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швеция',
        },
        {
          code: 9,
          name: 'Q&Q',
          price: 56,
          color: 'white',
          src: '../../assets/items/qq.png',
          rating: 3,
          gender: 'Детские',
          glass: 'Гексалитовое',
          brend: 'Q&Q',
          meha: 'кварцевые',
          belt: 'Полимер',
          waterproof: 'Водонепроницаемые',
          box: 'Полимер',
          country: 'Япония',
        },
        {
          code: 10,
          name: 'Cassio MTP',
          price: 336,
          color: 'gold',
          src: '../../assets/items/cassiomtp.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемыe',
          box: 'Латунь',
          country: 'Бельгия',
        },
        {
          code: 11,
          name: 'Cassio EFR',
          price: 422,
          color: 'grey',
          src: '../../assets/items/cassioefr.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 12,
          name: 'Q&Q HTN',
          price: 113,
          color: 'lightgrey',
          src: '../../assets/items/qqhtn.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          ' brend': 'Q&Q',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Япония',
        },
        {
          code: 13,
          name: 'Tissot Sera',
          price: 236,
          color: 'black',
          src: '../../assets/items/tissotsera.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 14,
          name: 'Q&Q VR',
          price: 77,
          color: 'violet',
          src: '../../assets/items/qqvr.png',
          rating: 3,
          gender: 'Детские',
          glass: 'Гексалитовое',
          brend: 'Q&Q',
          meha: 'кварцевые',
          belt: 'Акриловый',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Япония',
        },
        {
          code: 15,
          name: 'Cassio EFS',
          price: 412,
          color: 'grey',
          src: '../../assets/items/cassioefs.png',
          rating: 3,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 16,
          name: 'Tissot Chrono',
          price: 634,
          color: 'brown',
          src: '../../assets/items/tissotchrono.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 17,
          name: 'Perrier Ceramic',
          price: 232,
          color: 'black',
          src: '../../assets/items/perrierceramic.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Perrier',
          meha: 'кварцевые',
          belt: 'Керамика',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Франция',
        },
        {
          code: 18,
          name: 'Cassio LTP',
          price: 322,
          color: 'pink',
          src: '../../assets/items/cassioltp.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кож',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 19,
          name: 'Cardino',
          price: 121,
          color: 'grey',
          src: '../../assets/items/cardino.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Cardino',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 20,
          name: 'Tissot CERA',
          price: 155,
          color: 'white',
          src: '../../assets/items/tissotcera.png',
          rating: 5,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Керамика',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 21,
          name: 'Tissot Everytime',
          price: 256,
          color: 'red',
          src: '../../assets/items/tissoteverytime.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 22,
          name: 'Royal London',
          price: 152,
          color: 'gold',
          src: '../../assets/items/royallondon.png',
          rating: 3,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Royal',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Англия',
        },
        {
          code: 23,
          name: 'Tissot PR 100 Sport',
          price: 432,
          color: 'white',
          src: '../../assets/items/tissotprsport.png',
          rating: 5,
          gender: "'Женские",
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 24,
          name: 'Tissot Everytyme Small',
          price: 203,
          color: 'grey',
          src: '../../assets/items/tissoteverytimesmall.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 25,
          name: 'Cassio',
          price: 126,
          color: 'grey',
          src: '../../assets/items/cassio.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 26,
          name: 'Tissot Couturier',
          price: 244,
          color: 'grey',
          src: '../../assets/items/tissotcouturier.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 27,
          name: 'Perrier Lannier',
          price: 256,
          color: 'white',
          src: '../../assets/items/perrierlannier.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Perrier',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Розовое золото',
          country: 'Франция',
        },
        {
          code: 28,
          name: 'Swiss Military Hannova',
          price: 346,
          color: 'brown',
          src: '../../assets/items/swissmilitary.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Swiss',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швеция',
        },
        {
          code: 29,
          name: 'Q&Q',
          price: 56,
          color: 'white',
          src: '../../assets/items/qq.png',
          rating: 3,
          gender: 'Детские',
          glass: 'Гексалитовое',
          brend: 'Q&Q',
          meha: 'кварцевые',
          belt: 'Полимер',
          waterproof: 'Водонепроницаемые',
          box: 'Полимер',
          country: 'Япония',
        },
        {
          code: 30,
          name: 'Cassio MTP',
          price: 336,
          color: 'gold',
          src: '../../assets/items/cassiomtp.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемыe',
          box: 'Латунь',
          country: 'Бельгия',
        },
        {
          code: 31,
          name: 'Cassio EFR',
          price: 422,
          color: 'grey',
          src: '../../assets/items/cassioefr.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 32,
          name: 'Q&Q HTN',
          price: 113,
          color: 'lightgrey',
          src: '../../assets/items/qqhtn.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          ' brend': 'Q&Q',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Япония',
        },
        {
          code: 33,
          name: 'Tissot Sera',
          price: 236,
          color: 'black',
          src: '../../assets/items/tissotsera.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 34,
          name: 'Q&Q VR',
          price: 77,
          color: 'violet',
          src: '../../assets/items/qqvr.png',
          rating: 3,
          gender: 'Детские',
          glass: 'Гексалитовое',
          brend: 'Q&Q',
          meha: 'кварцевые',
          belt: 'Акриловый',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Япония',
        },
        {
          code: 35,
          name: 'Cassio EFS',
          price: 412,
          color: 'grey',
          src: '../../assets/items/cassioefs.png',
          rating: 3,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 36,
          name: 'Tissot Chrono',
          price: 634,
          color: 'brown',
          src: '../../assets/items/tissotchrono.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 37,
          name: 'Perrier Ceramic',
          price: 232,
          color: 'black',
          src: '../../assets/items/perrierceramic.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Perrier',
          meha: 'кварцевые',
          belt: 'Керамика',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Франция',
        },
        {
          code: 38,
          name: 'Cassio LTP',
          price: 322,
          color: 'pink',
          src: '../../assets/items/cassioltp.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кож',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 39,
          name: 'Cardino',
          price: 121,
          color: 'grey',
          src: '../../assets/items/cardino.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Cardino',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 40,
          name: 'Tissot CERA',
          price: 155,
          color: 'white',
          src: '../../assets/items/tissotcera.png',
          rating: 5,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Керамика',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 41,
          name: 'Tissot Everytime',
          price: 256,
          color: 'red',
          src: '../../assets/items/tissoteverytime.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 42,
          name: 'Royal London',
          price: 152,
          color: 'gold',
          src: '../../assets/items/royallondon.png',
          rating: 3,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Royal',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Англия',
        },
        {
          code: 43,
          name: 'Tissot PR 100 Sport',
          price: 432,
          color: 'white',
          src: '../../assets/items/tissotprsport.png',
          rating: 5,
          gender: "'Женские",
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 44,
          name: 'Tissot Everytyme Small',
          price: 203,
          color: 'grey',
          src: '../../assets/items/tissoteverytimesmall.png',
          rating: 4,
          gender: 'Женские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Не водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 45,
          name: 'Cassio',
          price: 126,
          color: 'grey',
          src: '../../assets/items/cassio.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Бельгия',
        },
        {
          code: 46,
          name: 'Tissot Couturier',
          price: 244,
          color: 'grey',
          src: '../../assets/items/tissotcouturier.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Tissot',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швейцария',
        },
        {
          code: 47,
          name: 'Perrier Lannier',
          price: 256,
          color: 'white',
          src: '../../assets/items/perrierlannier.png',
          rating: 3,
          gender: 'Женские',
          glass: 'Минеральное',
          brend: 'Perrier',
          meha: 'кварцевые',
          belt: 'Нержавеющая сталь',
          waterproof: 'Водонепроницаемые',
          box: 'Розовое золото',
          country: 'Франция',
        },
        {
          code: 48,
          name: 'Swiss Military Hannova',
          price: 346,
          color: 'brown',
          src: '../../assets/items/swissmilitary.png',
          rating: 5,
          gender: 'Мужские',
          glass: 'Сапфировое',
          brend: 'Swiss',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемые',
          box: 'Нержавеющая сталь',
          country: 'Швеция',
        },
        {
          code: 49,
          name: 'Q&Q',
          price: 56,
          color: 'white',
          src: '../../assets/items/qq.png',
          rating: 3,
          gender: 'Детские',
          glass: 'Гексалитовое',
          brend: 'Q&Q',
          meha: 'кварцевые',
          belt: 'Полимер',
          waterproof: 'Водонепроницаемые',
          box: 'Полимер',
          country: 'Япония',
        },
        {
          code: 50,
          name: 'Cassio MTP',
          price: 336,
          color: 'gold',
          src: '../../assets/items/cassiomtp.png',
          rating: 4,
          gender: 'Мужские',
          glass: 'Минеральное',
          brend: 'Cassio',
          meha: 'кварцевые',
          belt: 'Натуральная кожа',
          waterproof: 'Водонепроницаемыe',
          box: 'Латунь',
          country: 'Бельгия',
        },
      ];
      
      export default dataBase;
      